#!/usr/bin/env python3
"""Enriched Tier-2 text, chunk 2 (the Kingdom era)."""
import update_tier2

update_tier2.apply({
"hannah": [
  "There was a woman named Hannah who loved God with her whole heart. More than anything else in the whole world, she wanted to have a baby of her own.",
  "But year after year went by, and Hannah had no children. It made her very, very sad, and sometimes she cried and cried.",
  "One day, Hannah went to God's house all by herself. She wanted to talk to God about the sadness deep inside her heart.",
  "Hannah prayed and prayed. \"Dear God,\" she prayed, \"if you give me a son, I promise I will give him right back to you, to serve you his whole life long.\"",
  "Hannah prayed so quietly that her lips were moving but no sound came out. Only God could hear her quiet prayer.",
  "The priest, whose name was Eli, was watching. He thought something was wrong, but Hannah said, \"I am just praying to God from the bottom of my heart.\"",
  "Then Eli said something kind. \"Go in peace,\" he told her, \"and may God give you what you have asked him for.\"",
  "Hannah went home, and she was not sad anymore. She had given her heavy worry to God, and she trusted him with it.",
  "And God heard Hannah's prayer! After a while, Hannah had a baby boy. She named him Samuel, and she was so happy and thankful.",
  "Hannah did not forget the promise she had made to God. When Samuel was still a little boy, she brought him to God's house so he could serve God there, just as she had promised.",
  "It must have been so hard to say goodbye. But Hannah trusted God with the very gift she had begged for.",
  "Then Hannah sang a beautiful, happy song to thank God. \"My heart is so full of joy in the Lord!\" she sang.",
  "God had heard Hannah's quiet prayer and answered it. And God hears every one of our prayers too, even the quiet ones."
],
"saul-king": [
  "For a long, long time, God himself was the king of his people. He led them and he took care of them, and he was the very best king they could ever have.",
  "But the people looked at all the other nations around them. Those nations had kings with shiny crowns and tall thrones.",
  "So the people went to the prophet Samuel and said, \"We want a king too, just like all the other nations have!\"",
  "This made Samuel very sad. So he prayed about it, and God answered him.",
  "\"They are not really saying no to you,\" God told Samuel. \"They are saying no to me as their king. They want to be like everyone else.\"",
  "God told Samuel to warn the people first. \"A king will take your sons for his army,\" Samuel said. \"He will take your best fields and your animals, and one day you will be sorry.\"",
  "But the people would not listen. \"No!\" they said. \"We still want a king to rule over us!\"",
  "So God told Samuel to give them what they had asked for.",
  "God chose a young man named Saul to be the king. Saul was very tall, taller than everyone else, and he looked just like a king should look.",
  "And at first, Saul was humble. When the big day came to make him king, Saul was so shy that he went and hid behind the baggage!",
  "The people had to go and find him and bring him out. Then Samuel made Saul the king, and everyone shouted, \"Long live the king!\"",
  "Saul started out well. But the people would slowly learn an important lesson.",
  "No king they could see with their eyes could ever take the place of God, their one true King, who loved them best of all."
],
"david-anointed": [
  "King Saul had stopped following God and obeying him. So God had a brand new king in mind for his people.",
  "God sent the prophet Samuel to a little town called Bethlehem, to the house of a man named Jesse.",
  "\"One of Jesse's sons will be the next king,\" God told Samuel. \"I will show you which one.\"",
  "When Samuel arrived, Jesse lined up his sons. The oldest one stepped forward first. He was tall and strong and handsome.",
  "\"Surely this is the one God has chosen!\" Samuel thought to himself.",
  "But God said, \"No, not this one. Do not look at how tall he is or how he looks on the outside. People look at the outside, but I look at the heart.\"",
  "So Jesse called his next son, and the next, and the next. Seven big, strong sons walked past Samuel, and each time, God said, \"Not this one either.\"",
  "Samuel was puzzled. \"Are these all the sons you have?\" he asked Jesse.",
  "\"There is still my youngest son,\" said Jesse. \"His name is David, but he is out in the fields, watching the sheep.\"",
  "Nobody had even thought to call David in! So they ran out to the fields to get him.",
  "When David came in, with the wind and the sun on his face, God said, \"This is the one! Stand up and anoint him.\"",
  "So Samuel poured oil on David's head, right in front of all his big brothers, to show that David was God's chosen king.",
  "God did not pick David because he was the biggest or the strongest. God picked him because of what was in his heart. And God always sees what is inside each one of us."
],
"david-jonathan": [
  "After David bravely beat the giant Goliath, he came to live at the palace of King Saul.",
  "There, David met the king's son, Prince Jonathan. And from the very first day, something wonderful happened.",
  "Jonathan loved David like his own brother, and the two of them became the very best of friends.",
  "Jonathan even gave David his own royal robe, and his sword, and his bow. Jonathan was the prince, but he gladly shared everything he had with his friend.",
  "But there was a problem. Everyone loved David and sang happy songs about him. And this made King Saul very, very jealous.",
  "Saul got so jealous that he wanted to hurt David. Poor Jonathan was caught between his father and his best friend.",
  "Jonathan chose to do what was right. He warned David that he was in danger, and he even spoke up for David to his father.",
  "But Saul's jealousy came back, worse than before. So David and Jonathan made a secret plan to keep David safe.",
  "Jonathan would shoot some arrows in a field. If he shot them far away, it would be a secret signal that David must run away to stay safe.",
  "When Jonathan saw that his father really did want to hurt David, his heart was very sad. So he shot the arrows far out into the field.",
  "That was the signal. David knew he had to run away.",
  "Before David left, the two friends hugged each other and cried, because they did not know when they would see each other again.",
  "\"Go in peace,\" said Jonathan. \"We will always be friends.\" David and Jonathan loved each other and helped each other, and that is exactly what good friends do."
],
"david-ark": [
  "David was now the king of all of God's people. He wanted to bring something very special home to his city, Jerusalem.",
  "It was the ark of the covenant, a beautiful golden chest. The ark was a sign that God himself was right there with his people.",
  "David wanted God to be at the very center of his city and his whole life.",
  "So the people carried the ark carefully into the city, doing it the right way, just like God had said to.",
  "And what a celebration it was! There were trumpets and harps and tambourines.",
  "Everyone sang and shouted for joy as the ark of God came home to Jerusalem.",
  "King David was so full of happiness that he danced and danced with all his might, right down the middle of the street!",
  "He did not care one little bit how he looked. He just wanted to show God how much he loved him.",
  "But David's wife, Michal, watched from a window. She thought a king should not dance around like that, and she felt embarrassed by him.",
  "When David came home, she said, \"You looked so silly today!\"",
  "But David said, \"I was dancing for God! I do not care if I look silly. I just want to give God all my praise and honor.\"",
  "David loved God so much that his joy came bursting right out of him.",
  "Worshiping God is not about looking proper or fancy. It is about loving God with your whole heart, exactly the way David did."
],
"mephibosheth": [
  "David was now the king. He was safe and strong, sitting on his throne in the palace.",
  "One day, David remembered his very best friend, Jonathan, who had died. Long ago, David had made Jonathan a promise to always be kind to his family.",
  "So David asked his servants, \"Is there anyone left from Jonathan's family that I can show kindness to?\"",
  "There was one person. Jonathan had a son named Mephibosheth, who was all grown up now.",
  "When Mephibosheth was just a little boy, he had been hurt in both of his feet, and he could not walk.",
  "For a long time, Mephibosheth had been hiding far away. He was scared that the new king would want to get rid of him.",
  "So David sent for him. Poor Mephibosheth was shaking with fear as he was carried in before the king. He was sure he was in big trouble.",
  "But David said gently, \"Do not be afraid! I am going to be kind to you, because I loved your father, Jonathan.\"",
  "\"I am giving you back all of your grandfather's land,\" said David. \"And from now on, you will eat here at my table with me every single day, just like one of my own sons.\"",
  "Mephibosheth could hardly believe his ears! \"Why would you be so kind to someone like me?\" he asked.",
  "He had walked in expecting the worst, and instead he was given a home, and land, and a special place at the king's table forever.",
  "Mephibosheth did nothing to earn all that kindness. It was all because of David's love for his friend.",
  "And that is exactly how God welcomes us to be with him, not because we have earned it, but simply because he loves us so very much."
],
"david-bathsheba": [
  "David was a great king who loved God very much. The Bible tells us about the good things David did, but it also tells us the truth about his mistakes.",
  "One day, David made some very bad and very selfish choices. He did something that was wrong, and he hurt someone in the process.",
  "After David did the wrong thing, he tried to keep it a secret. He hoped and hoped that no one would ever find out.",
  "On the outside, it looked like nobody knew what David had done. Life just went on as usual.",
  "But there was Someone who saw everything. God knew exactly what David had done, even the parts that no person had seen.",
  "But God loved David far too much to just leave him stuck in his sin. So God sent a brave helper, a prophet named Nathan, to talk to David.",
  "Nathan did not yell at David. Instead, he told the king a story. \"There was a rich man who had everything,\" said Nathan, \"but he stole a poor man's one little lamb.\"",
  "When David heard the story, he got very angry. \"That is so unfair!\" he said. \"That rich man should be punished!\"",
  "Then Nathan looked David right in the eye and said, \"You are that man.\"",
  "Suddenly, David understood. The story was about him! And David did not make any excuses.",
  "\"I have sinned against the Lord,\" he said. David was truly, deeply sorry for what he had done.",
  "And God, who is full of mercy, forgave him. There were still some sad things that happened because of David's choices, but David was forgiven.",
  "We cannot hide our wrong things from God, and we do not need to. When we tell God we are sorry, he always forgives us, just like he forgave David."
],
"solomon-temple": [
  "King David had always dreamed of building a beautiful house for God, a special place where everyone could come to worship him.",
  "But God told David that his son would be the one to build it. So when David's son Solomon became king, he set out to build a wonderful temple for God.",
  "It was a huge and important job! Solomon gathered the finest cedar wood from far away and the very best stone from the quarries.",
  "Thousands and thousands of workers helped to build it. And it took seven whole years to finish.",
  "Here is something amazing about the temple. All the stones were cut and shaped far away, before they were brought to the building site.",
  "So the whole temple was built without the sound of a single hammer! It rose up quietly and peacefully.",
  "Inside, the temple was beautiful. The walls were carved with flowers and palm trees, and they were covered all over with shining gold.",
  "In the very center was the most special room of all. There, they carefully placed the ark of the covenant. At last, it had a forever home.",
  "When everything was finished, a thick cloud filled the whole temple. It was the glory of God! God himself had come to fill his house.",
  "Then Solomon stood up and prayed in front of all the people. He spread out his hands toward heaven.",
  "\"God,\" he prayed, \"you are so big that even all of heaven cannot hold you. How wonderful that you would come and meet with us here!\"",
  "Solomon knew that no building, no matter how grand and golden, could ever hold the great big God who made everything.",
  "And here is the very best part. Today, God comes to live right inside the hearts of people who love him. We get to be God's home!"
],
"naboth": [
  "King Ahab had a big palace and lots of riches. He had almost everything a person could want.",
  "But there was one little thing that Ahab did not have. Right next to his palace was a vineyard, like a garden, and it belonged to his neighbor, a man named Naboth.",
  "\"Naboth, sell me your vineyard,\" said King Ahab. But Naboth said, \"I am sorry, but I cannot. This land belongs to my family. God gave it to us long ago.\"",
  "When Ahab heard this, he was so upset that he went to his room, lay down on his bed, turned his face to the wall, and would not even eat his dinner.",
  "He had almost everything in the world, but he pouted and sulked about the one little thing he could not have.",
  "Now Ahab's wife was a wicked queen named Jezebel. \"Are you not the king?\" she said. \"Get up and eat. I will get you that vineyard myself.\"",
  "And then Jezebel did a truly wicked thing. She told terrible lies about Naboth.",
  "Because of those lies, poor Naboth was treated very unfairly, and he lost his life. It was a terrible thing to do.",
  "Then Jezebel told Ahab, \"Now the vineyard is yours.\" So Ahab went down to take it, as if nothing was wrong at all.",
  "But Someone had seen the whole thing. God saw everything that had happened to Naboth.",
  "So God sent the prophet Elijah to King Ahab. \"You have done a very wicked thing,\" Elijah told him. \"And God saw it all.\"",
  "Naboth had no one powerful to protect him. But he was never truly alone, because God saw, and God cared about him.",
  "Our God always sees when people are treated unfairly, and he cares about everyone, especially those who need help."
],
"naaman": [
  "Naaman was the leader of a great big army. He was a strong and important man, and everyone respected him.",
  "But Naaman had a problem that he could not fix. He had a bad skin sickness called leprosy, and all his money and power could not make it go away.",
  "Now, a young servant girl from Israel lived in Naaman's house. She had been taken far from her home, but she was still kind.",
  "\"I wish my master could see the prophet who lives in Israel,\" she said. \"That prophet could make him well again!\"",
  "So Naaman traveled all the way to Israel to find the prophet Elisha. He brought horses and chariots and lots of treasure.",
  "But when he got there, Elisha did not even come outside. He just sent a messenger to the door with a simple message.",
  "\"Go and wash in the Jordan River seven times,\" the message said, \"and you will be all better.\"",
  "Naaman was very angry! \"I thought the prophet would come out and do something big and fancy!\" he said. \"And the Jordan is just a muddy little river!\" And he stomped away.",
  "But Naaman's servants spoke to him gently. \"Master,\" they said, \"if the prophet had asked you to do something hard, you would have done it. So why not try this simple thing?\"",
  "So Naaman swallowed his pride and went down to the river. He dipped under the water one time, two times, all the way to seven times, just as Elisha had said.",
  "And when he came up the seventh time, his skin was completely healed! It was fresh and new, like the skin of a little child.",
  "Naaman was amazed and so thankful. \"Now I know,\" he said, \"that the God of Israel is the one true God!\"",
  "And it all began because one young servant girl was brave and kind enough to speak up. God can use anyone who trusts him, even you!"
],
"axe-head": [
  "A group of God's helpers lived and worked together with the prophet Elisha. But their home had gotten too small for all of them.",
  "\"Let us go down to the Jordan River,\" they said, \"and each chop down a tree, so we can build ourselves a bigger place to live.\"",
  "Elisha said yes, and he went along with them. When they got to the river, everyone got busy chopping down trees.",
  "But while one man was chopping really hard, the heavy iron head flew right off the top of his axe!",
  "It went sailing through the air and splashed into the deep river, sinking down, down, down, out of sight.",
  "\"Oh no!\" the man cried out. \"That axe was not even mine. I borrowed it from someone!\"",
  "Back in those days, iron cost a lot of money, and the poor man knew he could never buy a new one to give back.",
  "\"Where did it fall in?\" Elisha asked him. The man pointed to the exact spot in the water where the axe head had disappeared.",
  "Then Elisha did something surprising. He cut a stick and threw it into the river, right where the axe head had sunk.",
  "And the heavy iron axe head floated right up to the top of the water, as light as a little leaf!",
  "\"Reach out and grab it,\" said Elisha. The man reached down and took it, hardly able to believe his own eyes.",
  "It was such a small thing, just one borrowed tool. But God still cared about it.",
  "And that shows us something wonderful. God cares about the little things in our lives too. Nothing is ever too small to bring to God."
],
"widows-oil": [
  "One day, a poor woman came to the prophet Elisha, crying. She was very worried and afraid.",
  "Her husband had died, and now she owed money that she could not pay back.",
  "\"The man we owe is coming to take my two sons away to work for him!\" she said. She was about to lose her boys, and she did not know what to do.",
  "\"How can I help you?\" asked Elisha kindly. \"Tell me, what do you have in your house?\"",
  "The woman shook her head sadly. \"I have nothing at all,\" she said, \"except one little jar of oil.\" It was the very last thing she owned.",
  "But that little jar was exactly what God would use! \"Go,\" said Elisha, \"and borrow lots of empty jars from all your neighbors. Get as many as you possibly can!\"",
  "So the woman and her two sons hurried around and gathered empty jars from everyone, until they had a great big pile of them.",
  "Then they went inside, shut the door, and the woman began to pour her one little jar of oil into the empty jars.",
  "And the oil just kept pouring and pouring! She filled up one jar, and there was still more. She filled another, and another, and the oil did not run out!",
  "\"Bring me another jar!\" she kept saying to her sons. They ran back and forth until at last every single jar was full to the top.",
  "Only when there were no more empty jars did the oil finally stop flowing.",
  "The woman sold all that oil, paid back the money she owed, and still had plenty left over for her family. Her boys were safe!",
  "She had given God only the tiniest little bit, but God turned it into more than enough. God loves to do big things with the little we give him."
],
"shunammite": [
  "In a town called Shunem lived a kind and generous woman. Whenever the prophet Elisha came through her town, she invited him in for a good meal.",
  "One day she said to her husband, \"Let us build a little room on our roof for this man of God, with a bed and a table, so he always has a place to rest.\"",
  "She was so kind, and she never asked for a single thing in return.",
  "Elisha wanted to do something kind for her too. He found out that she had always wished for a child of her own.",
  "So Elisha told her, \"About this time next year, you will be holding a baby boy in your arms.\" And just as he said, the woman had a son!",
  "The little boy grew bigger, and he was the joy of his mother's heart.",
  "But one day, the boy got very, very sick. His mother held him on her lap, but the little boy died.",
  "The woman was so sad. But she did not give up, because she trusted God. She laid her son on Elisha's bed and hurried off as fast as she could to find the prophet.",
  "Elisha came back to the house with her. He went into the room where the boy was lying, and he shut the door, and he prayed to God.",
  "Then he stretched himself out over the little boy, and slowly, the child's body grew warm again.",
  "And then the little boy sneezed and opened his eyes! He was alive again!",
  "\"Come and take your son,\" Elisha said. The happy mother scooped up her boy and held him close, and she thanked God with her whole heart.",
  "This woman had been kind and full of faith. And God showed her, long before Jesus ever came, that he is even stronger than death itself."
],
})
