#!/usr/bin/env python3
"""Enriched Tier-2 text, chunk 3 (Daniel + early ministry + parables)."""
import update_tier2

update_tier2.apply({
"daniel-food": [
  "A long, long way from home, in a land called Babylon, lived a young man named Daniel and his three good friends.",
  "They had been taken away from their home in Jerusalem to serve the king in his great big palace. It was a strange new place, far from everything they knew.",
  "The king said that these young men should eat the very best food from his own royal table every day.",
  "But Daniel knew that some of that food went against God's ways. So Daniel decided, deep in his heart, that he would honor God instead.",
  "It took real courage. Daniel was far from home, and everyone around him was doing things differently. It would have been so easy to just go along with the crowd.",
  "Instead, Daniel politely asked the man in charge, \"Please, may my friends and I eat only vegetables and drink only water?\"",
  "The man was worried. \"But the king chose your food himself,\" he said. \"If you look thin and weak, the king will be angry with me!\"",
  "So Daniel had a good idea. \"Just test us for ten days,\" he said. \"Give us only vegetables and water. Then see how we look compared to everyone else.\"",
  "The man agreed to try it for ten days.",
  "When the ten days were over, Daniel and his three friends looked healthier and stronger than all the other young men who ate the king's rich food!",
  "So they were allowed to keep eating their simple food. And God was pleased with them.",
  "God gave Daniel and his friends great wisdom, more than anyone else in the whole kingdom.",
  "Daniel honored God even in a small, everyday choice about his dinner. And the little choices we make to follow God are very important too."
],
"wise-men": [
  "Far away in lands to the east, there lived wise men who studied the stars in the night sky.",
  "One night, they saw a brand new star, brighter and more wonderful than any star they had ever seen before.",
  "The wise men knew that this special star meant something amazing. A great new king had been born to God's people!",
  "So they packed up some precious gifts and set out on a very long journey to find the new king and worship him.",
  "When they came to the city of Jerusalem, they asked everyone, \"Where is the baby who has been born to be king? We saw his star, and we have come to worship him.\"",
  "When King Herod heard this, he was troubled and upset. He was the king, and he did not want anyone taking his place.",
  "Herod found out from the wise teachers that the special king was to be born in a town called Bethlehem.",
  "So the wise men set off again. And the wonderful star went ahead of them, leading the way, until it stopped right over the place where the child was.",
  "The wise men were filled with joy! They went inside and saw the young child Jesus with his mother, Mary.",
  "They knelt down low to the ground and worshiped him.",
  "Then they opened their treasures and gave Jesus their very best gifts: shiny gold, and sweet-smelling frankincense and myrrh.",
  "They had traveled such a very long way, not to see a fancy palace, but to kneel down before one special child and give him their best.",
  "The wise men teach us something wonderful. We can seek Jesus with all our hearts, and we can worship him by giving him our very best too."
],
"baptism": [
  "Out in the wilderness, near the Jordan River, a man named John was preaching to anyone who would listen.",
  "John looked a little wild. He wore rough clothes made of camel hair, and he ate locusts and wild honey.",
  "\"Turn back to God!\" John told the crowds. \"Get your hearts ready, because someone much greater than me is coming soon.\"",
  "People who were sorry for the wrong things they had done came to John. He baptized them in the river, dipping them under the water, to show that they were starting fresh and clean with God.",
  "Then one day, Jesus himself came to the river. And he asked John to baptize him too.",
  "John was very surprised. \"It should be the other way around!\" he said. \"You should baptize me!\"",
  "You see, Jesus had never done anything wrong, so he did not need to be washed clean like the others.",
  "But Jesus said, \"Let it be this way. It is the right thing for us to do.\" Jesus wanted to stand together with all the people he came to save. So John baptized him.",
  "The very moment Jesus came up out of the water, something wonderful happened. The sky opened up above him!",
  "The Spirit of God came down softly, gently, like a dove, and rested on Jesus.",
  "And then God the Father spoke from heaven. \"This is my Son, whom I love,\" he said. \"With him I am very pleased.\"",
  "God said that he loved his Son before Jesus had done any miracles or preached any sermons at all.",
  "And that is exactly how God loves you. Not because of what you do, but simply because you are his child."
],
"temptation": [
  "Right after Jesus was baptized, the Spirit of God led him out into the lonely desert.",
  "Jesus stayed there for forty days and forty nights, and he did not eat any food the whole time. He was praying and getting ready for the important work ahead.",
  "By the end of the forty days, Jesus was very, very hungry.",
  "That is when the devil came to tempt him, to try to get him to do wrong.",
  "\"If you really are the Son of God,\" said the devil, \"then turn these stones into bread!\"",
  "But Jesus said no. He answered with God's own words: \"People do not live on bread alone, but on every word that comes from God.\"",
  "The devil tried again. He took Jesus up to a very high place. \"Jump off!\" he said. \"God's angels will catch you.\"",
  "But Jesus said, \"No. The Bible says we must not test God.\"",
  "Then the devil showed Jesus all the kingdoms of the whole world. \"I will give all of this to you,\" he said, \"if you will just bow down and worship me.\"",
  "But Jesus said firmly, \"Go away! The Bible says we must worship and serve only God.\"",
  "Three times the devil tried to get Jesus to do wrong. And three times, Jesus said no by trusting God and remembering God's words.",
  "Finally, the devil gave up and went away. Then angels came and took care of Jesus.",
  "Jesus knows exactly what it feels like to be tempted to do wrong. So when we are tempted, Jesus understands, and he helps us to do what is right."
],
"call-disciples": [
  "Jesus began to travel from town to town, telling people the good news about God's kingdom.",
  "One day, Jesus was walking beside a big, beautiful lake called the Sea of Galilee.",
  "Lots of people worked at that lake, catching fish to sell. It was hard work, and they did it every day.",
  "As Jesus walked along, he saw two brothers, Simon Peter and Andrew. They were busy throwing their fishing net into the water.",
  "Jesus called out to them, \"Come, follow me! And I will make you fishers of people!\"",
  "And right away, the two brothers left their nets behind and followed Jesus.",
  "A little farther down the shore, Jesus saw two more brothers, James and John. They were sitting in a boat with their father, fixing their nets.",
  "Jesus called them too. And right away, they left their boat and their father and went to follow Jesus.",
  "Now think about this. Jesus did not go to a palace to find kings, or to a school to find the smartest teachers.",
  "Instead, Jesus walked along a lake and chose ordinary, hardworking fishermen to be his friends and followers.",
  "And when Jesus called them, they did not wait or make excuses. They got up and followed him right away.",
  "Over time, Jesus gathered twelve special followers, called disciples. They were just ordinary people, but Jesus loved them and taught them.",
  "And Jesus still calls ordinary people like us today. He simply says, \"Come, follow me!\""
],
"cana": [
  "Jesus, his mother Mary, and his friends were all invited to a big wedding party in a town called Cana.",
  "Back in those days, a wedding was a huge celebration with lots of food and fun. It could go on for many days!",
  "But right in the middle of the party, something went wrong. They ran out of wine to drink.",
  "This was very embarrassing for the family who was hosting the wedding. They did not know what to do.",
  "Mary noticed the problem. She went to Jesus and said simply, \"They have no more wine.\"",
  "Then Mary turned to the servants nearby and told them, \"Do whatever Jesus tells you to do.\"",
  "Standing close by were six great big stone jars. Jesus said to the servants, \"Fill the jars up with water.\" So they filled them all the way to the top.",
  "Then Jesus said, \"Now dip some out and take it to the man in charge of the party.\"",
  "The servants did exactly what Jesus said, wondering what would happen.",
  "But when the man in charge tasted it, the water had turned into wine! And it was not just any wine. It was the very best wine of all!",
  "\"Most people serve the best wine first,\" he said, surprised, \"but you have saved the best for last!\"",
  "This was the very first miracle that Jesus ever did. It showed everyone how amazing and powerful he is, and his friends believed in him.",
  "Jesus did his first miracle at a happy wedding. That shows us that Jesus cares about our happy times too, and whatever he touches, he makes wonderfully good."
],
"sower": [
  "One day, such a big crowd came to hear Jesus teach that he got into a boat and pushed out a little way from the shore.",
  "That way, all the people standing on the beach could see and hear him. Then Jesus taught them with a story.",
  "\"A farmer went out to plant his seeds,\" Jesus began. \"And as he scattered them, the seeds fell on four different kinds of ground.\"",
  "\"Some of the seeds fell on the hard path. And the birds quickly flew down and gobbled them all up.\"",
  "\"Some of the seeds fell on rocky ground. They sprouted up fast, but their roots could not go down deep. So when the hot sun came out, the little plants dried up and died.\"",
  "\"Some of the seeds fell among thorny weeds. The seeds started to grow, but the prickly weeds grew up too and crowded out the little plants.\"",
  "\"But some of the seeds fell on good, soft soil. Those seeds grew up strong and healthy and made lots and lots of new grain!\"",
  "Later, Jesus told his friends what the story really meant.",
  "The seed, he said, is God's word, the good news about him. And the different kinds of ground are like the different ways people's hearts receive it.",
  "The hard path is a heart that hears God's word but does not understand it. The rocky ground is a heart that gives up when trouble comes.",
  "The thorny ground is a heart that lets worries crowd God's word out. But the good soil is a heart that hears God's word, holds it close, and lets it grow.",
  "Jesus wants each of us to have a heart like the good soil.",
  "When we listen to God's word and hold on to it, it grows in us and makes our lives beautiful and good, like a field full of grain."
],
"mustard-seed": [
  "One day, Jesus wanted to help people understand what God's kingdom is like. So he told them a short story about a very small seed.",
  "\"The kingdom of heaven,\" Jesus said, \"is like a tiny little mustard seed that a man planted in his garden.\"",
  "Now, a mustard seed is one of the very smallest seeds of all.",
  "You could hold a whole big bunch of them in the palm of your hand. And if you dropped just one on the ground, you might not even be able to find it again!",
  "It really does look like nothing important at all.",
  "\"But when that tiny little seed is planted and begins to grow,\" Jesus went on, \"it becomes the biggest plant in the whole garden.\"",
  "\"It grows into a tree so big and so tall that the birds of the sky come and build their nests in its branches!\"",
  "The smallest seed you can imagine grows into a tree big enough to give the birds a home. That is what God's kingdom is like.",
  "God's kingdom often starts in ways that look tiny and unimportant. It started with a baby born in a stable. It started with twelve ordinary followers.",
  "It can start with one small act of love, or one quiet prayer.",
  "But God takes those small beginnings and grows them into something far bigger and more beautiful than anyone could ever imagine.",
  "So we never have to feel like we are too small, or that the little things we do for God do not matter.",
  "In God's hands, even the tiniest seed of faith and love can grow into something truly wonderful."
],
"lost-sheep": [
  "Some people did not like that Jesus was so kind to people who had done wrong things. They grumbled about it.",
  "So Jesus told them a story to help them understand God's heart.",
  "\"Imagine that you have a hundred sheep,\" said Jesus, \"and one of them wanders off and gets lost.\"",
  "\"What would you do? Wouldn't you leave the ninety-nine other sheep and go out to look for the one that is lost, until you found it?\"",
  "Every single sheep was special to the shepherd. He would not just shrug and say, \"Oh well, I still have ninety-nine.\"",
  "That one little lost sheep, all alone and scared, was worth going after.",
  "So the shepherd went looking. He climbed up the hills and down through the valleys, calling and searching, until at last he found his lost little sheep!",
  "And when he found it, he was not even angry. He was filled with joy!",
  "Gently, the shepherd lifted the sheep up and laid it across his shoulders. Then he carried it all the way home.",
  "When he got home, he called all his friends and neighbors together. \"Be happy with me!\" he said. \"I have found my lost sheep!\"",
  "Then Jesus explained the story. \"In the very same way,\" he said, \"all of heaven is filled with joy when even one lost person comes back to God.\"",
  "Jesus is just like that good shepherd. He loves every single one of us so much.",
  "You are never too lost or too far away for Jesus to come looking for you. And when you are found, all of heaven celebrates!"
],
"lost-coin": [
  "Right after Jesus told the story of the lost sheep, he told another little story that meant the very same thing.",
  "\"Imagine that a woman has ten silver coins,\" said Jesus, \"and one day, she loses one of them.\"",
  "Those ten coins were very precious to the woman. They might have been all the money she had in the whole world.",
  "So losing even one of them made her very sad and worried.",
  "What did the woman do? Did she just shrug and say, \"Oh well, I still have nine\"? No, she did not!",
  "Instead, she lit a lamp to brighten up the house. Then she got a broom and swept the floor, looking carefully in every single corner.",
  "She searched and searched, low and high, and she would not stop looking until she found that one lost coin.",
  "And then, at last, she found it! Oh, how happy she was!",
  "The woman was so full of joy that she ran to call all her friends and neighbors together.",
  "\"Be happy with me!\" she said. \"I have found my lost coin!\" Her joy was so big that she just could not keep it to herself.",
  "Then Jesus told everyone what the story meant. \"In the very same way,\" he said, \"the angels of heaven are filled with joy when even one lost person comes back to God.\"",
  "You are so very precious to God, just like that one special coin.",
  "God never loses interest and never gives up. And when one lost person is found, all of heaven breaks into a happy celebration!"
],
"paralytic": [
  "One day, Jesus was teaching inside a house in a town called Capernaum.",
  "So many people had crowded inside to hear him that there was no room left at all, not even outside the door!",
  "Now, in that town lived a man who could not walk. And this man had four very good friends.",
  "His four friends believed that if they could just get their friend to Jesus, Jesus could make him well.",
  "So they carried their friend on his sleeping mat, all the way to the house. But when they got there, they could not get in. It was just too crowded.",
  "But these friends did not give up! They had a bold idea.",
  "They carried their friend up the outside stairs, all the way to the flat roof of the house. Then they began to dig a hole right through the roof!",
  "When the hole was big enough, they carefully lowered their friend down on his mat, right in front of Jesus.",
  "When Jesus saw how much the four friends believed, he was very pleased. He looked at the man on the mat and said, \"Your sins are forgiven.\"",
  "Some of the teachers sitting there were surprised, because only God can forgive sins. They did not understand that Jesus is God.",
  "Then Jesus said to the man, \"Get up, pick up your mat, and go home.\"",
  "And right away, the man stood up! He picked up his mat and walked out through the crowd, all better. Everyone was amazed and praised God.",
  "Good friends bring each other to Jesus. And Jesus made that man well, both inside and out."
],
"calm-storm": [
  "After a long day of teaching, Jesus said to his friends, \"Let us go across to the other side of the lake.\"",
  "So they all climbed into a boat together and started to sail across the Sea of Galilee.",
  "Jesus was very tired. So he went to the back of the boat, rested his head on a soft cushion, and fell fast asleep.",
  "But suddenly, without any warning, a fierce storm came roaring down on the lake.",
  "The wind howled, and the waves grew bigger and bigger. They crashed right over the sides of the boat, and water started pouring in.",
  "The disciples were terrified, even though many of them were fishermen who knew the lake well.",
  "But through it all, Jesus kept sleeping peacefully in the back of the boat.",
  "The disciples could not believe it. They shook him awake, crying out, \"Teacher! Don't you care that we are about to drown?\"",
  "Jesus stood up in the rocking boat. He spoke to the wind, and he said to the crashing waves, \"Quiet! Be still!\"",
  "And in an instant, the wind stopped blowing, and the water became perfectly calm and smooth. The storm was completely gone!",
  "Then Jesus turned to his friends. \"Why were you so afraid?\" he asked them gently. \"Don't you trust me yet?\"",
  "The disciples were filled with wonder. \"Who is this?\" they whispered to each other. \"Even the wind and the waves obey him!\"",
  "Jesus was with them in the boat the whole time. And when we are scared, Jesus is with us too. We can always trust him."
],
})
