#!/usr/bin/env python3
"""Enriched Tier-2 text, chunk 1 (Patriarchs / Exodus / Promised Land)."""
import update_tier2

update_tier2.apply({
"jacob-ladder": [
  "Jacob had to run away from home, because his brother Esau was very angry with him.",
  "He walked a long, long way, all by himself. He had no friends with him and no cozy place to sleep.",
  "When the sun went down, Jacob was out in the wild, and there was nowhere to rest. There were no beds and no soft pillows anywhere at all.",
  "So Jacob found a smooth stone, put his head on it like a pillow, and lay down on the hard ground. He felt lonely and very far from home.",
  "But while Jacob was sleeping, God gave him an amazing dream.",
  "In his dream, Jacob saw a giant stairway. It started on the ground and went up, up, up, all the way into heaven!",
  "And on the stairway were the angels of God, going up and coming down, up and down between heaven and earth.",
  "At the very top of the stairway stood God himself. And God spoke kindly to Jacob.",
  "\"I am with you,\" God said. \"I will watch over you everywhere you go, and I will bring you back home again one day. I will never, ever leave you.\"",
  "When Jacob woke up, he was filled with wonder. \"God is right here in this place,\" he said, \"and I did not even know it!\"",
  "In the morning, Jacob stood his stone pillow up tall to help him always remember this special day. He named the place Bethel, which means the house of God.",
  "Jacob had felt all alone in the dark. But God had been with him the whole time. And God is always with you too, even when you cannot see him."
],
"jacob-wrestles": [
  "After many years away, Jacob was finally going back home. But he was very, very scared.",
  "Jacob was scared because he had to see his brother Esau again. The last time they were together, Esau had been so angry with him.",
  "The night before they would meet, Jacob sent his whole family across a river to keep them safe. Then he stayed behind, all by himself, in the dark.",
  "Suddenly, a man came out of the dark and started to wrestle with Jacob.",
  "They wrestled and wrestled, back and forth, all night long. Neither one of them would give up!",
  "When morning was almost there, the man said, \"Let me go now.\"",
  "But Jacob held on tight. \"I will not let you go,\" he said, \"until you give me a blessing.\"",
  "The man asked him, \"What is your name?\" \"My name is Jacob,\" he answered.",
  "Then the man said, \"Your new name will be Israel, because you have held on to God and would not give up.\"",
  "Suddenly Jacob understood something amazing. He had been wrestling with God the whole time!",
  "Jacob named that special place Peniel. \"I have seen God face to face,\" he said, with wonder in his heart.",
  "When the sun came up, Jacob walked toward his brother, and he was limping a little. Jacob used to grab for everything he wanted. But that night, he learned to hold on tight to God instead."
],
"plagues": [
  "God's people, the Israelites, had been slaves in the land of Egypt for a very, very long time. They worked hard all day long, and they cried out to God to please save them.",
  "So God sent a man named Moses to the king of Egypt, who was called Pharaoh. Moses stood before the king and said, \"God says, let my people go!\"",
  "But Pharaoh did not want to lose all his workers. He folded his arms and said, \"No! I will not let them go.\"",
  "So God sent troubles on Egypt called plagues. First, Moses held his hand over the river, and all the water turned to blood.",
  "Then frogs came hopping up out of the river, thousands and thousands of them, into the houses and the beds and even the cooking pots!",
  "After the frogs came tiny biting bugs, and then big, buzzing clouds of flies all over Egypt.",
  "Next, the farm animals got sick, and the people got itchy, sore skin. Then big chunks of hail came crashing down from the sky, and hungry locusts ate up every green plant that was left.",
  "Last of all, a thick darkness covered Egypt for three whole days. It was so dark that no one could even see their own hand in front of their face.",
  "But here is the wonderful part. Where God's people lived, it stayed bright and sunny the whole time. God kept his people safe through every single plague.",
  "Every time a plague came, Moses said, \"Let God's people go.\" And every time, Pharaoh was stubborn and said no.",
  "God was showing Pharaoh, and everyone in Egypt, that he is stronger than any king in the whole world.",
  "And one more plague was still coming, the very last one, the one that would finally set God's people free."
],
"passover": [
  "God said that one last plague would finally set his people free from Egypt. But first, he gave them a special way to stay safe that night.",
  "God told each family to pick a perfect little lamb, one with nothing wrong with it at all.",
  "That evening, the families would gather together, and they would paint some of the lamb's blood on the sides and the top of their front door.",
  "Then they cooked the lamb and ate it with flat bread. They put on their coats and their shoes and held their walking sticks, all ready to leave the very moment God said go.",
  "God told them, \"When I come through Egypt tonight and I see the blood on your door, I will pass right over your house. No harm will come to anyone inside.\"",
  "So the families waited inside their homes, trusting God. And in the middle of the night, God passed through all of Egypt.",
  "Every single house that had the blood on the door was kept safe, and everyone inside was protected. The blood showed that the people inside belonged to God.",
  "That very night, Pharaoh finally called for Moses. \"Go!\" he cried. \"Take your families, take your animals, take everything, and leave!\"",
  "So God's people walked out of Egypt as free people at last, after such a very long time.",
  "God told them to remember this special night every single year, with a special meal. They called it the Passover, because God had passed over them and kept them safe.",
  "And there was a wonderful secret hidden in that night. Long, long after, a man named John would point to Jesus and say, \"Look, the Lamb of God!\"",
  "Jesus is the Lamb who keeps us safe forever. The very first Passover was pointing to him all along."
],
"manna": [
  "Out in the hot, dry desert, the people of Israel ran out of food. They were hungry and afraid, and they began to grumble.",
  "\"We wish we were back in Egypt,\" they complained, \"where we had plenty to eat! Did you bring us out here just to let us starve?\"",
  "But God was very kind to them. He told Moses, \"I will send bread down from heaven for you, every single day.\"",
  "That evening, a big flock of birds called quail came right into the camp, so the people had meat to eat for dinner.",
  "And the next morning, when the dew dried up, there were little white flakes all over the ground, like frost. The people had never seen anything like it before.",
  "They asked each other, \"What is it? What is it?\" So they gave it that very name: manna, which means, what is it?",
  "The manna was white like a tiny seed, and it tasted sweet, a little like honey. The people gathered it up and ate it, and it was good.",
  "God told them to gather just enough for one day. But some people did not listen, and they kept extra overnight. In the morning, it was full of worms and smelled terrible!",
  "On the sixth day, God told them to gather twice as much, because the seventh day was a special day to rest. On that day, no manna would fall, and the extra they saved stayed fresh and good.",
  "God did not send manna for just a few days. He sent it every single morning for forty years, until his people finally reached the land he had promised them.",
  "God gave his people exactly what they needed, one day at a time. He always took care of them.",
  "And God still takes care of us, giving us just what we need, one day at a time. We can always trust him."
],
"golden-calf": [
  "Moses went up a tall mountain to meet with God and to get his rules for living. He was gone for a long, long time, forty days and forty nights.",
  "Down at the bottom of the mountain, the people got tired of waiting. They went to Moses' brother Aaron with a bad idea.",
  "\"We do not know what happened to Moses,\" they said. \"Make us a god that we can see!\"",
  "And instead of saying no, Aaron gave in. \"Bring me your gold earrings,\" he said.",
  "So Aaron took all their gold, melted it in the fire, and shaped it into a shiny golden calf. The people bowed down low to it and had a big, wild party.",
  "But this was very, very wrong. They were forgetting the real God, the one who had just saved them from Egypt with his mighty power.",
  "Way up on the mountain, God told Moses what the people were doing. So Moses hurried back down, carrying two flat stones with God's words written on them.",
  "When Moses saw the golden calf and the wild party, his heart filled with sadness and anger.",
  "He was so upset that he dropped the two stones, and they smashed into pieces on the ground.",
  "Moses melted the golden calf in the fire until there was nothing left of it. Then he asked Aaron, \"Why did you let the people do such a terrible thing?\"",
  "The next day, Moses went back up the mountain. \"Please forgive your people,\" he begged God. He loved them so much.",
  "And God, who is slow to get angry and full of love, forgave the people and stayed with them. They had been quick to forget God, but God would never give up on them."
],
"bronze-serpent": [
  "The people of Israel had been traveling through the desert for a long, long time, and they were getting grumpy and tired.",
  "They complained against God again, even about the good food that he sent them fresh every single day.",
  "Because of all their grumbling, snakes came slithering into the camp. Many of the people got hurt, and everyone was very scared.",
  "The people ran to Moses and said, \"We are so sorry! We should not have complained against God. Please ask him to help us.\"",
  "So Moses prayed to God for the people. And God gave Moses a surprising answer.",
  "God said, \"Make a snake out of shiny bronze, and put it up high on a tall pole.\"",
  "Then God made a promise. \"Anyone who has been hurt can look up at the bronze snake, and they will get better.\"",
  "So Moses made the bronze snake and lifted it up high on the pole, right in the middle of the camp where everyone could see it.",
  "There was no medicine to take and nothing hard to do. The people who were hurt just looked up at the snake, and they got well again!",
  "All they had to bring was their trust. Looking up was their way of saying, \"God, I believe that you can save me.\"",
  "Long, long after this, Jesus told this very story. He said that he would be lifted up high too, on a cross.",
  "And just like the people who looked at the snake and lived, everyone who looks to Jesus and trusts him will be saved. When we need help, we can always look to Jesus."
],
"spies": [
  "After many years in the desert, God's people finally came right up to the edge of the new land that God had promised to give them.",
  "God told Moses to choose twelve men and send them ahead to explore the land and see what it was like.",
  "For forty days, the twelve men walked all around the land. It was beautiful, just like God had said, and it was full of good things to eat.",
  "The men even found a bunch of grapes so big and so heavy that it took two men to carry it on a pole between them!",
  "But when the twelve men came back, ten of them were very scared. \"There are giants in that land,\" they said, \"and huge cities with walls as tall as the sky! We can never go in there.\"",
  "When the people heard this, they got very afraid. They cried all night long, and they forgot how big and strong their God was.",
  "But two of the men, Caleb and Joshua, were brave and full of faith. \"Do not be afraid!\" they said. \"God is with us. He will help us go in and live there.\"",
  "Sadly, the people listened to their fear instead of trusting God.",
  "Because they would not trust him, the people had to wait out in the desert for a very long time before they could go into the good land.",
  "But Caleb and Joshua had trusted God. And one day, they got to go into the wonderful land God promised.",
  "The giants were big, that was true. But God was even bigger than any giant.",
  "And whenever we feel scared, we can remember that our God is bigger than anything that frightens us."
],
"balaam": [
  "God's people set up their camp near a land called Moab. The king of Moab was very afraid of them, because there were so very many of them.",
  "So the king sent for a man named Balaam. He offered Balaam lots and lots of money to come and say bad, cursing words against God's people.",
  "But God told Balaam, \"Do not curse them. They are my people, and they are blessed.\"",
  "Still, Balaam really wanted that money. So he got on his donkey and started off to go anyway.",
  "God was not happy about this. So an angel with a shiny sword came and stood right in the middle of the road. But only the donkey could see the angel, not Balaam!",
  "To stay safe, the donkey kept turning away from the angel. But Balaam could not see why, so he hit his donkey to make her keep going.",
  "This happened three times. The poor donkey was just trying to keep Balaam safe!",
  "Then God did something truly amazing. He let the donkey talk! \"Why are you hitting me?\" she asked Balaam.",
  "Then God opened Balaam's eyes, and at last he could see the angel standing in the road. Balaam was very sorry.",
  "His donkey had been protecting him the whole time, and he had not even known it.",
  "After that, every single time Balaam opened his mouth to say bad words about God's people, only good and happy words came out instead!",
  "No one in the whole world can curse the people God has blessed. God was taking care of his people, even when they did not know it."
],
"jordan": [
  "After many years of traveling, God's people finally came to a big river called the Jordan. They needed to cross it to reach the new home God had promised them.",
  "But the river was very deep and wide and rushing fast, and there was no bridge and no boats anywhere.",
  "Their brave new leader was a man named Joshua. God told him exactly what to do.",
  "\"Have the priests carry the special golden chest, the ark, into the river first,\" God said.",
  "So the priests lifted up the ark and carried it down to the edge of the rushing water. Then they stepped right in.",
  "And the very moment their feet touched the river, the water stopped flowing! It piled up high, far away, and the ground in the middle of the river became dry.",
  "Then all of God's people walked across the river on the dry ground. They stayed perfectly safe and perfectly dry!",
  "God told Joshua to have twelve men each pick up a big stone from the middle of the river.",
  "They piled the stones up on the other side, to help everyone remember this amazing day forever.",
  "\"In the future,\" said Joshua, \"when your children ask, what are these stones for, you can tell them how God stopped the river.\"",
  "Long ago, God had stopped the sea so the people's parents could escape from Egypt. And now God stopped the river so the children could go into the promised land.",
  "God was showing his people that he would always be with them and always take care of them, no matter what."
],
"deborah": [
  "After Joshua died, God's people kept forgetting God and getting into trouble. But God was kind, and he sent special helpers called judges to rescue them.",
  "One of the very best judges was a wise woman named Deborah.",
  "Deborah would sit under a big palm tree, and people came from all around to ask her to help them solve their problems and to hear from God.",
  "In those days, a mean king and his army had been hurting God's people for a long, long time. The army had nine hundred strong iron chariots, and the people were very scared.",
  "So Deborah called for a soldier named Barak. \"God says to take an army to the top of the mountain,\" she told him. \"And God will help you win!\"",
  "But Barak was afraid to go. \"I will only go,\" he said, \"if you come with me.\"",
  "So brave Deborah went with him to the battle.",
  "When it was time to fight, Deborah said, \"Go now! This is the day God is going to help you win!\"",
  "Then God sent a big rainstorm. The ground turned to thick, sticky mud, and all the enemy's heavy chariots got stuck and could not move at all!",
  "So God's people won the battle, and at last they were safe. God had rescued them again.",
  "Then Deborah sang a happy song to thank God for saving his people.",
  "God can use anyone who trusts him, men or women, young or old, to do brave and wonderful things."
],
"samson": [
  "God's people were having a hard time, so God sent a special baby boy named Samson to help save them.",
  "Before Samson was even born, an angel said that he must never, ever cut his hair. It was a special sign that Samson belonged to God.",
  "When Samson grew up, God gave him amazing strength. He was the strongest man that anyone had ever seen!",
  "As long as Samson kept his promise and did not cut his hair, no one could ever beat him.",
  "But sadly, Samson did not always make good choices, and he did not always listen to God.",
  "One day, a woman named Delilah kept asking Samson why he was so very strong. She asked him again and again.",
  "Finally, Samson told her his secret. \"My strength comes from God,\" he said, \"and the sign is my long hair, which has never been cut.\"",
  "That night, while Samson was sleeping, his enemies came and cut off his hair. When Samson woke up, his great strength was gone.",
  "His enemies caught him and put him in prison. It was a very sad time for Samson.",
  "But slowly, while he was in prison, his hair began to grow back again.",
  "One day, his enemies brought Samson out to laugh at him in their big building. Samson prayed, \"God, please give me my strength just one more time.\"",
  "And God did! Samson pushed against the big stone pillars, and the whole building came tumbling down. Even after all of Samson's mistakes, God still listened when he prayed. God is strong, and he loves to help us when we ask him."
],
})
