#!/usr/bin/env python3
"""Enriched Tier-2 text, chunk 4 (more miracles + the early church)."""
import update_tier2

update_tier2.apply({
"bartimaeus": [
  "One day, Jesus was leaving the town of Jericho, and a big crowd of people was following along with him.",
  "Beside the road sat a blind man named Bartimaeus. Because he could not see, he could not work, so he sat there and begged people for help.",
  "When Bartimaeus heard that Jesus was coming down the road, his heart leaped with hope.",
  "He began to shout out as loud as he could, \"Jesus! Please have mercy on me!\"",
  "Some of the people in the crowd told him to be quiet. \"Hush!\" they said. \"Stop making such a noise!\"",
  "But Bartimaeus would not stop. He just shouted even louder, \"Jesus, please have mercy on me!\"",
  "Then Jesus stopped walking. In the middle of that whole big crowd, Jesus stood still. \"Call him over here,\" he said.",
  "Suddenly the people changed their tune. \"Cheer up!\" they told Bartimaeus. \"Get up! Jesus is calling for you!\"",
  "Bartimaeus threw off his coat, jumped up, and hurried over to Jesus as fast as he could.",
  "\"What do you want me to do for you?\" Jesus asked him kindly.",
  "\"Teacher,\" said Bartimaeus, \"I want to see!\"",
  "\"Go,\" said Jesus. \"Your faith has made you well.\" And right away, Bartimaeus could see!",
  "The very first thing his eyes ever saw was the kind, loving face of Jesus.",
  "And then Bartimaeus did something wonderful. He followed Jesus right down the road. Jesus always hears us when we call out to him, and he stops for every single person."
],
"jairus": [
  "A man named Jairus was an important leader in his town. But one day, he came to Jesus as a scared and worried father.",
  "Jairus fell down at Jesus' feet and begged him, \"My little girl is so sick. Please come and put your hands on her, so she will get well!\" His daughter was only twelve years old.",
  "So Jesus went with Jairus toward his house. But the crowd was so big, pushing in on every side, that they could only walk very slowly.",
  "Jairus must have been so worried, because every moment counted.",
  "Then, before they could get to the house, some people came with terrible news. \"Your daughter has died,\" they said. \"There is no need to bother the teacher anymore.\"",
  "It seemed like all hope was gone. But Jesus heard the news, and he turned to Jairus.",
  "\"Do not be afraid,\" Jesus said gently. \"Just believe.\"",
  "When they reached the house, it was full of people crying and weeping with sadness.",
  "Jesus said to them, \"Why all this crying? The little girl is not dead. She is only sleeping.\" And the people laughed at him, because they were sure she was gone.",
  "But Jesus sent everyone outside. Then he took the girl's mother and father, and three of his friends, into the room where she was lying.",
  "Jesus gently took the little girl by the hand and said, \"Little girl, I say to you, get up.\"",
  "And right away, the little girl stood up and began to walk around! Her mother and father were filled with amazement and joy.",
  "Then Jesus, so kind and caring, told them to give her something to eat. Jesus is powerful enough to defeat even death, and he is gentle and loving too. Nothing is ever hopeless with him."
],
"ten-lepers": [
  "One day, as Jesus was traveling along, he came near a village where ten men were waiting. All ten of them had a terrible skin sickness called leprosy.",
  "Because they were sick, these men were not allowed to live with everyone else. They had to stay far away from their families and friends. They were very lonely.",
  "Since they could not come close, the ten men stood at a distance and called out together as loud as they could.",
  "\"Jesus, Master, please have mercy on us!\" they cried.",
  "When Jesus saw them, he felt sorry for them. \"Go,\" he said, \"and show yourselves to the priests.\"",
  "Now, only a priest could say a person was healed and could go home. So Jesus was asking the men to start walking before anything had even happened. He was asking them to trust him.",
  "And the ten men did! They obeyed and started off down the road.",
  "And as they were walking, an amazing thing happened. Their skin became clean and healthy. Every single one of them was completely healed!",
  "Nine of the men were so excited that they hurried off to start their new lives. But one of the men stopped.",
  "When he saw that he was healed, he turned around and came running back to Jesus, praising God at the top of his voice!",
  "He threw himself down at Jesus' feet and said thank you, again and again. And this man was a foreigner, someone many people looked down on.",
  "Jesus looked around and asked, \"Weren't all ten of them healed? Where are the other nine? Only this one came back to say thank you.\"",
  "All ten men received the wonderful gift of healing. But only one remembered to come back and say thank you.",
  "God gives us so many good gifts every day. Let us always remember, like that one thankful man, to stop and say thank you to God."
],
"blesses-children": [
  "Everywhere that Jesus went, people wanted to be close to him.",
  "One day, some parents started bringing their little children to Jesus. They hoped that Jesus would put his hands on them and bless them.",
  "Mothers and fathers carried their babies and led their little ones toward Jesus.",
  "But the disciples did not like this at all. They thought that Jesus was much too busy and important for little children.",
  "So the disciples tried to shoo the families away. \"Do not bother the teacher!\" they said.",
  "When Jesus saw what his disciples were doing, he was not happy with them at all.",
  "\"Let the little children come to me,\" Jesus said firmly. \"Do not ever stop them! For the kingdom of God belongs to children just like these.\"",
  "The disciples had it all backward. They thought the children were not important enough. But Jesus said God's kingdom belongs to them!",
  "Then Jesus said something even more surprising. \"Anyone who wants to come into God's kingdom,\" he said, \"must come like a little child.\"",
  "He meant that everyone, even grown-ups, must come to God simply and trustingly, the way a child does.",
  "And then Jesus did exactly what the parents had hoped for. He took the children up into his arms, one by one.",
  "He put his hands on them and blessed them. Jesus was never, ever too busy for the children. He had time for every single one of them.",
  "Jesus loves children, and that means he loves you! You are never too small or too young for Jesus. He always says, \"Come to me!\""
],
"mary-martha": [
  "One day, Jesus came to visit two sisters named Martha and Mary, who lived together in a town called Bethany.",
  "Martha was so happy to have Jesus as her guest. She wanted everything to be just perfect for him.",
  "So Martha got very, very busy. There was a meal to cook, and a house to clean, and so much to do.",
  "She rushed all around the house, working hard to get everything ready.",
  "But her sister Mary did something different. Mary came and sat down at Jesus' feet.",
  "And she just listened, quietly drinking in every word that Jesus said.",
  "This started to bother Martha more and more. She was doing all the work, while her sister just sat there!",
  "Finally, Martha came to Jesus, feeling a little upset. \"Lord,\" she said, \"don't you care that my sister has left me to do all the work by myself? Please tell her to come and help me!\"",
  "Jesus answered her gently and with great love. \"Martha, Martha,\" he said kindly, \"you are worried and upset about so many things.\"",
  "\"But really, only one thing is needed,\" Jesus told her. \"Mary has chosen the better thing, and it will not be taken away from her.\"",
  "Martha was not wrong to work hard, and she was not wrong to want to be a good host.",
  "But in all of her busyness, she had nearly missed the most important thing of all, which was simply spending time with Jesus.",
  "It is good to be helpful and to work hard. But Jesus reminds us that nothing in the whole world is more important than stopping to be with him."
],
"peter-beggar": [
  "One afternoon, Peter and John were on their way to the temple to pray.",
  "At the temple gate sat a man who had never been able to walk in his whole life.",
  "Every single day, his friends carried him to that gate, so he could beg for coins from the people going in to worship.",
  "When the man saw Peter and John coming, he asked them for some money, just as he asked everyone.",
  "Peter looked straight at the man. \"Look at us,\" he said. The man looked up, hoping to get a coin or two.",
  "But Peter said something surprising. \"I do not have any silver or gold,\" he said. \"But what I do have, I will give to you!\"",
  "\"In the name of Jesus Christ,\" said Peter, \"get up and walk!\"",
  "Then Peter took the man by his right hand and helped him up.",
  "And instantly, the man's feet and ankles became strong! For the very first time in his life, he was standing up!",
  "The man jumped to his feet, and then he began to walk. Then he started leaping and jumping for joy!",
  "He went right into the temple with Peter and John, walking and jumping and praising God as loud as he could.",
  "Everyone who saw him was filled with wonder, because they knew he was the same man who used to sit and beg at the gate.",
  "It was not Peter's own power that healed the man. It was the wonderful power of Jesus' name. Jesus was still helping and healing people, now through his followers."
],
"philip-ethiopian": [
  "One day, an angel told a man named Philip to go to a lonely desert road. Philip did not know why, but he obeyed God and went.",
  "Along that road came a chariot. Inside it rode an important official from a faraway land called Ethiopia.",
  "This man was in charge of all the queen's treasure. He had traveled a very long way to worship God in Jerusalem.",
  "Now, on his way home, he was reading out loud from God's word, the scroll of the prophet Isaiah.",
  "God's Spirit said to Philip, \"Go over and walk near that chariot.\" So Philip ran up to it.",
  "As he got close, Philip heard the man reading. \"Do you understand what you are reading?\" Philip asked him.",
  "\"How can I understand,\" said the man, \"unless someone explains it to me?\" And he kindly invited Philip to climb up and sit beside him.",
  "The man pointed to the words and asked, \"Who is the prophet talking about here?\"",
  "So Philip, beginning right there with those very words, told the man all about the good news of Jesus.",
  "He explained that Isaiah had written about Jesus, the one who gave his life to save us, hundreds of years before Jesus was even born!",
  "As they rode along together, they came to some water. \"Look, here is water!\" said the man. \"What is stopping me from being baptized?\"",
  "So they stopped the chariot, and Philip baptized him right there, to show that the man now belonged to Jesus.",
  "Then the happy man went on his way home, ready to tell others. God had sent Philip to a lonely road for one searching heart, because the good news of Jesus is for everyone, everywhere."
],
"cornelius": [
  "In a city called Caesarea lived a Roman soldier named Cornelius. He was not one of God's people Israel, but he loved God, prayed often, and was kind to the poor.",
  "One day, an angel appeared to Cornelius. \"God has heard your prayers,\" the angel said. \"Send for a man named Peter.\" So Cornelius sent messengers to go and find him.",
  "Meanwhile, Peter was up on a rooftop, praying. He got hungry, and while he waited for food, he had a strange vision, like a dream.",
  "Peter saw a huge sheet come down from heaven, full of all kinds of animals, even ones that God's people were not supposed to eat.",
  "A voice said, \"Get up, Peter. Eat.\" But Peter said, \"No, Lord! I have never eaten anything like that.\"",
  "Then the voice said, \"Do not call anything bad that God has made good.\" This happened three times, and Peter wondered what it could mean.",
  "Just then, Cornelius's messengers arrived at the door. And God's Spirit told Peter to go with them.",
  "Now in those days, Jewish people did not usually go into the homes of people from other nations. But Peter was starting to understand his vision.",
  "When Peter arrived at the house, it was full of Cornelius's family and friends, all waiting to hear him.",
  "\"Now I understand,\" Peter said. \"God does not have favorites. He welcomes people from every single nation who love him!\"",
  "Then Peter told them all the good news about Jesus, how he died and rose again to save anyone who believes.",
  "And while Peter was still speaking, the Holy Spirit came down on everyone listening, just like at Pentecost! People from another nation had received the very same gift.",
  "So they were all baptized. The good news of Jesus had burst past every wall and every border. It really is for the whole wide world, including you!"
],
"peter-escapes": [
  "A wicked king named Herod was hurting the church, and he threw Peter into prison.",
  "Peter was guarded by soldiers on every side. He was even chained between two of them, with more guards at the door. There seemed to be no way out at all.",
  "But Peter's friends in the church did the most powerful thing they could do. They gathered together and prayed for Peter, all through the night.",
  "On the very night before his trial, Peter was sound asleep, chained between the two soldiers.",
  "Suddenly, an angel of the Lord appeared, and a bright light filled the whole prison cell!",
  "The angel tapped Peter on the side and woke him up. \"Quick, get up!\" said the angel. And the chains fell right off of Peter's wrists!",
  "\"Get dressed and follow me,\" said the angel. Peter did, but he was so amazed that he thought he must be dreaming.",
  "They walked right past the first group of guards, and then the second group. Nobody stopped them!",
  "When they came to the big iron gate that led into the city, it swung open all by itself! They walked through and down the street, and then the angel suddenly disappeared.",
  "Only then did Peter understand. \"Now I know for sure,\" he said, \"that God sent his angel and rescued me!\"",
  "Peter hurried to the house where all his friends were still praying for him. He knocked on the door.",
  "A servant girl named Rhoda heard his voice. She was so overjoyed that she ran to tell everyone, but she forgot to open the door, and left Peter knocking outside!",
  "At first, no one believed her. But Peter kept knocking, and when they finally opened the door, they were amazed. God had answered their prayers while they were still praying them!"
],
"athens": [
  "Paul came to a famous city called Athens. It was full of clever thinkers and grand, beautiful buildings.",
  "But as Paul walked around the city, his heart felt troubled. Everywhere he looked, there were idols, statues of pretend gods, on every corner.",
  "Paul began to tell people in the marketplace the good news about Jesus.",
  "The famous thinkers of Athens were curious about him. \"This man has some new ideas,\" they said. \"Let us hear what he has to say.\"",
  "So they brought Paul to a special hill where people gathered to talk about big questions.",
  "Paul stood up and said, \"People of Athens! I can see that you are very religious. As I walked around, I even found an altar with these words on it: TO A GOD WE DO NOT KNOW.\"",
  "\"You worship a god you do not even know,\" said Paul. \"Well, let me tell you who he is!\"",
  "\"The God who made the whole world and everything in it,\" Paul said, \"is the Lord of heaven and earth. He does not live inside statues built by people.\"",
  "\"He does not need anything from us,\" Paul went on, \"because he is the one who gives life and breath to every living thing. And he is not far away from any one of us.\"",
  "Paul told them that the real God is alive. He is not like gold or stone shaped by human hands. He made us, and we are his children!",
  "Then Paul told them the most important news of all. God now asks everyone, everywhere, to turn to him. And God proved that Jesus is Lord by raising him from the dead.",
  "When some of the people heard about someone rising from the dead, they laughed and sneered. But others said, \"We want to hear more about this!\"",
  "And some of them believed. Even in a city full of pretend gods, the truth about the one true God found its way into hearts that were ready to listen."
],
"eutychus": [
  "Paul was visiting his friends, the believers, in a town called Troas.",
  "Because Paul was leaving the very next morning, he had so much that he wanted to say to them.",
  "So everyone gathered together in an upstairs room. The room was warm, and it was lit by many flickering lamps.",
  "Paul began to teach, and he talked on and on, late into the night.",
  "Now, sitting in an open window was a young man named Eutychus.",
  "As Paul kept on preaching, and the hour grew later and later, poor Eutychus began to get very, very sleepy.",
  "His eyes grew heavy, and his head started to nod. And then, sound asleep, Eutychus tumbled right out of the window!",
  "It was a long, long way down to the ground below. When the people rushed down and picked him up, the young man had died.",
  "What a terrible, sad moment! The happy gathering had suddenly turned to crying. But Paul hurried down the stairs to the boy.",
  "Paul bent down and threw his arms around the young man, holding him close.",
  "Then Paul stood up and said, \"Do not be afraid! He is alive!\"",
  "And it was true! The young man was alive and well again! The people could hardly believe their happy relief.",
  "Then they all went back upstairs, shared a meal together, and Paul kept right on talking until the sun came up!",
  "God turned their sadness back into joy. He is the God of life, and he can always bring hope, even out of our saddest moments."
],
"shipwreck": [
  "Paul was being taken on a big ship across the sea, all the way to the great city of Rome.",
  "But not long into the trip, the weather turned terrible. A furious wind, the kind sailors feared the most, caught the ship and pushed it helplessly across the sea.",
  "The storm was so bad that the sailors threw the ship's cargo overboard to make it lighter.",
  "Day after day went by with no sun and no stars to be seen, and the wild wind never stopped blowing.",
  "At last, everyone on board gave up all hope. They were sure they were going to be lost in the storm.",
  "But then Paul stood up among the frightened people. \"Keep up your courage!\" he said.",
  "\"Last night, an angel of God stood beside me,\" Paul told them. \"The angel said, Do not be afraid, Paul. And God will keep safe everyone who is sailing with you.\"",
  "\"So keep up your courage,\" Paul said, \"because I trust God. It will happen just as he told me. Not one of us will be lost!\"",
  "There were two hundred and seventy-six people on that ship. And in the middle of the worst storm of their lives, Paul was the calmest one of all, because he trusted God's promise.",
  "Finally, after many days, the ship came near land. But it crashed onto a sandbar and started to break apart in the pounding waves.",
  "So Paul told everyone to head for the shore. Those who could swim jumped in first. The others grabbed onto planks and broken pieces of the ship and floated in.",
  "And it happened just as God had promised! Every single one of the two hundred and seventy-six people reached the land safely.",
  "The ship was gone, but not one life was lost. God had kept his word, and Paul's trust in God had given courage to everyone around him."
],
})
